"use client";
import { useState } from "react";
import { VIRTUES, getSubVirtue, getVirtueParent, type ChildProfile } from "@/lib/data";
import { T, VC, btn, inputStyle } from "@/lib/tokens";

export default function StoryGenerator({ child }: { child: ChildProfile }) {
  const [generating, setGenerating] = useState(false);
  const [story, setStory] = useState<{ title: string; body: string } | null>(null);
  const [selectedVirtue, setSelectedVirtue] = useState("");
  const [customSituation, setCustomSituation] = useState("");
  const [error, setError] = useState<string | null>(null);
  const [emailAddress, setEmailAddress] = useState("");
  const [emailSent, setEmailSent] = useState(false);

  const generateStory = async () => {
    if (!selectedVirtue) return;
    setGenerating(true); setError(null); setStory(null); setEmailSent(false);
    const sv = getSubVirtue(selectedVirtue);
    const pk = getVirtueParent(selectedVirtue);
    const pv = pk ? VIRTUES[pk] : null;
    if (!sv || !pv) { setError("Invalid virtue."); setGenerating(false); return; }

    const ageLabel = child.age <= 4 ? "a very young child (ages 2-4)" :
      child.age <= 7 ? "a young child (ages 5-7)" :
      child.age <= 10 ? "a child (ages 8-10)" : "an older child (ages 11-13)";

    const prompt = `You are a master storyteller in the tradition of Aesop, the Brothers Grimm, and C.S. Lewis. Write an original children's story that teaches the virtue of ${sv.name} (${sv.desc}), which falls under the cardinal virtue of ${pv.name}.

The story is for ${child.name}, ${ageLabel}, who is ${child.sex === "boy" ? "a boy" : "a girl"}.
Reading level: ${child.readingLevel}.
${customSituation ? `The child is currently dealing with: ${customSituation}. Weave this theme naturally into the story.` : ""}

Requirements:
- ${child.age <= 5 ? "300-500" : child.age <= 8 ? "500-800" : "800-1200"} words
- Vivid, memorable characters and settings
- The moral emerges naturally, never stated explicitly
- Show virtue practiced through action and habit
- Rich, beautiful language for the reading level
- Include a compelling title
- Classical storytelling tradition
- No modern ideology or didactic lecturing

Format: Title on first line, then the story.`;

    try {
      const response = await fetch("/api/generate", {
        method: "POST", headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ prompt }),
      });
      const data = await response.json();
      if (data.error) setError(data.error);
      else if (data.text) {
        const lines = data.text.split("\n");
        const title = lines[0].replace(/^#+\s*/, "").replace(/^\*+/, "").replace(/\*+$/, "").trim();
        setStory({ title, body: lines.slice(1).join("\n").trim() });
      } else setError("No story generated. Try again.");
    } catch { setError("Failed to connect."); }
    setGenerating(false);
  };

  const exportPDF = () => {
    if (!story) return;
    const win = window.open("", "_blank");
    if (!win) return;
    win.document.write(`<!DOCTYPE html><html><head><title>${story.title}</title>
      <style>
        @import url('https://fonts.googleapis.com/css2?family=Crimson+Text:wght@400;600;700&display=swap');
        body { font-family: 'Crimson Text', Georgia, serif; max-width: 650px; margin: 40px auto; padding: 40px; color: #1D2939; line-height: 1.9; }
        h1 { text-align: center; font-size: 28px; color: #0A1628; border-bottom: 3px solid #D4A846; padding-bottom: 16px; margin-bottom: 24px; }
        .meta { text-align: center; font-size: 14px; color: #8892A4; margin-bottom: 32px; }
        p { font-size: 17px; margin-bottom: 16px; }
        .footer { margin-top: 40px; text-align: center; font-size: 13px; color: #C8CED9; border-top: 1px solid #E4E7EC; padding-top: 16px; }
      </style>
    </head><body>
      <h1>${story.title}</h1>
      <div class="meta">A story for ${child.name} · Generated by Virtue Forge</div>
      ${story.body.split("\n\n").map((p: string) => `<p>${p}</p>`).join("")}
      <div class="footer">⚒ Virtue Forge — Building Character Through Story</div>
    </body></html>`);
    win.document.close();
    setTimeout(() => win.print(), 500);
  };

  const sendEmail = () => {
    if (!story || !emailAddress) return;
    const subject = encodeURIComponent(`Story for ${child.name}: ${story.title}`);
    const body = encodeURIComponent(`${story.title}\n\nA story for ${child.name}, generated by Virtue Forge.\n\n${story.body}\n\n---\n⚒ Virtue Forge — Building Character Through Story`);
    window.open(`mailto:${emailAddress}?subject=${subject}&body=${body}`);
    setEmailSent(true);
  };

  return (
    <div>
      <div style={{ marginBottom: 20 }}>
        <label style={{ fontSize: 16, fontWeight: 700, color: T.navy, display: "block", marginBottom: 8 }}>
          Which virtue should this story teach?
        </label>
        <select value={selectedVirtue} onChange={(e) => setSelectedVirtue(e.target.value)} style={{ ...inputStyle }}>
          <option value="">Choose a virtue...</option>
          {Object.entries(VIRTUES).map(([key, v]) => (
            <optgroup key={key} label={`${v.icon} ${v.name}`}>
              {v.subVirtues.map((sv) => (
                <option key={sv.id} value={sv.id}>{sv.name} — {sv.desc}</option>
              ))}
            </optgroup>
          ))}
        </select>
      </div>

      <div style={{ marginBottom: 20 }}>
        <label style={{ fontSize: 16, fontWeight: 700, color: T.navy, display: "block", marginBottom: 8 }}>
          Specific situation (optional)
        </label>
        <input value={customSituation} onChange={(e) => setCustomSituation(e.target.value)}
          placeholder="e.g., struggling to share with a new sibling" style={inputStyle} />
      </div>

      <button onClick={generateStory} disabled={!selectedVirtue || generating}
        style={{ ...btn(generating ? T.gray400 : T.navy, generating ? T.white : T.gold),
          cursor: generating ? "wait" : "pointer", fontSize: 18, padding: "14px 32px" }}>
        {generating ? "⚒ Forging story..." : "⚒ Forge Story"}
      </button>

      {error && <div style={{ color: T.red, marginTop: 14, fontSize: 16, fontWeight: 600 }}>{error}</div>}

      {story && (
        <div style={{ marginTop: 32 }}>
          {/* Story display */}
          <div style={{ padding: 36, borderRadius: 12, background: T.white,
            border: `2px solid ${T.gold}50`, boxShadow: T.shadowLg }}>
            <h3 style={{ fontFamily: T.font, fontSize: 30, fontWeight: 700, color: T.navy,
              textAlign: "center", borderBottom: `3px solid ${T.gold}`, paddingBottom: 16, marginBottom: 24 }}>
              {story.title}
            </h3>
            <div style={{ fontFamily: T.font, fontSize: 18, lineHeight: 1.9, color: T.gray800,
              whiteSpace: "pre-wrap" }}>
              {story.body}
            </div>
          </div>

          {/* Export controls */}
          <div style={{ marginTop: 20, padding: 24, borderRadius: 10,
            background: T.gray50, border: `1px solid ${T.gray100}` }}>
            <div style={{ fontSize: 17, fontWeight: 700, color: T.navy, marginBottom: 16 }}>
              📤 Save & Share This Story
            </div>

            <div style={{ display: "flex", gap: 12, flexWrap: "wrap", marginBottom: 16 }}>
              <button onClick={exportPDF} style={{
                ...btn(T.navy, T.gold), fontSize: 15, padding: "10px 22px",
              }}>
                📄 Save as PDF
              </button>
              <button onClick={() => {
                if (story) navigator.clipboard.writeText(`${story.title}\n\n${story.body}`);
              }} style={{
                ...btn(T.white, T.navy, `2px solid ${T.navy}`), fontSize: 15, padding: "10px 22px",
              }}>
                📋 Copy Text
              </button>
            </div>

            <div style={{ display: "flex", gap: 10, alignItems: "center" }}>
              <input value={emailAddress} onChange={(e) => { setEmailAddress(e.target.value); setEmailSent(false); }}
                placeholder="Email address" type="email"
                style={{ ...inputStyle, flex: 1, fontSize: 15 }} />
              <button onClick={sendEmail} disabled={!emailAddress}
                style={{ ...btn(emailAddress ? T.gold : T.gray200, emailAddress ? T.navy : T.gray400),
                  fontSize: 15, padding: "12px 20px", whiteSpace: "nowrap" }}>
                {emailSent ? "✓ Opened" : "✉ Email Story"}
              </button>
            </div>
            {emailSent && (
              <div style={{ fontSize: 14, color: T.green, marginTop: 8 }}>
                Email client opened. Send the email to complete delivery.
              </div>
            )}
          </div>
        </div>
      )}
    </div>
  );
}
