"use client";
import { T } from "@/lib/tokens";
import { ArrowLeft, Shield } from "lucide-react";

export default function TermsOfService({ onBack }: { onBack: () => void }) {
  const h2Style: React.CSSProperties = {
    fontFamily: T.fontSans, fontSize: 22, fontWeight: 700,
    color: T.navy, marginTop: 40, marginBottom: 12,
  };
  const pStyle: React.CSSProperties = {
    fontFamily: T.fontSans, fontSize: 15, color: T.gray600,
    lineHeight: 1.75, marginBottom: 12,
  };
  const liStyle: React.CSSProperties = {
    fontFamily: T.fontSans, fontSize: 15, color: T.gray600,
    lineHeight: 1.75, marginBottom: 6,
  };

  return (
    <div style={{ minHeight: "100vh", background: T.white }}>
      <nav style={{
        background: "rgba(255,255,255,0.92)", backdropFilter: "blur(12px)",
        borderBottom: `1px solid ${T.gray100}`,
      }}>
        <div style={{
          maxWidth: 700, margin: "0 auto", padding: "0 24px",
          display: "flex", alignItems: "center", height: 56,
        }}>
          <button onClick={onBack} style={{
            display: "flex", alignItems: "center", gap: 6,
            fontFamily: T.fontSans, fontSize: 14, fontWeight: 500,
            color: T.gray600, background: "none", border: "none", cursor: "pointer",
          }}>
            <ArrowLeft size={16} />
            Back
          </button>
        </div>
      </nav>

      <div style={{ maxWidth: 700, margin: "0 auto", padding: "48px 24px 80px" }}>
        <div style={{ display: "flex", alignItems: "center", gap: 10, marginBottom: 8 }}>
          <Shield size={20} color={T.gold} />
          <span style={{ fontFamily: T.fontSans, fontSize: 13, fontWeight: 600, color: T.gold, textTransform: "uppercase", letterSpacing: "0.06em" }}>
            Legal
          </span>
        </div>

        <h1 style={{
          fontFamily: T.fontSans, fontSize: "clamp(28px, 4vw, 40px)",
          fontWeight: 800, color: T.navy, lineHeight: 1.15,
          marginBottom: 8,
        }}>
          Terms of Service
        </h1>
        <p style={{ fontFamily: T.fontSans, fontSize: 14, color: T.gray400, marginBottom: 32 }}>
          Last Updated: March 7, 2026
        </p>

        <p style={pStyle}>
          These Terms of Service (&ldquo;Terms&rdquo;) govern your use of Bedtime Virtues, operated at bedtimevirtues.com
          (the &ldquo;Service&rdquo;). By using the Service, you agree to these Terms.
        </p>

        <h2 style={h2Style}>1. Description of Service</h2>
        <p style={pStyle}>
          Bedtime Virtues provides AI-generated stories for character education, a curated library of
          children&apos;s books mapped to classical virtues, and virtue progress tracking tools.
          The Service is designed for use by parents and guardians on behalf of their children.
        </p>

        <h2 style={h2Style}>2. AI-Generated Content</h2>
        <p style={pStyle}>
          Stories generated by Bedtime Virtues are created using artificial intelligence (Anthropic&apos;s Claude).
          While we employ content safety measures and guardrails, AI-generated content may occasionally
          contain unexpected material. <strong>Parents and guardians must review all AI-generated stories
          before sharing them with children.</strong>
        </p>
        <p style={pStyle}>
          AI-generated stories are provided for entertainment and character education purposes.
          They are not a substitute for professional advice, therapy, or counseling.
        </p>

        <h2 style={h2Style}>3. Parental Responsibility</h2>
        <p style={pStyle}>
          You represent that you are at least 18 years old and are the parent or legal guardian of any
          child whose information you provide to the Service. You are responsible for reviewing all
          content generated by the Service before sharing it with your child.
        </p>

        <h2 style={h2Style}>4. User Accounts &amp; Data</h2>
        <p style={pStyle}>
          When used without an account, data is stored locally in your browser. When used with an account,
          you are responsible for maintaining the security of your login credentials. You may delete your
          account and all associated data at any time by contacting us.
        </p>

        <h2 style={h2Style}>5. Subscriptions &amp; Payments</h2>
        <p style={pStyle}>
          Bedtime Virtues offers a free tier and a Premium subscription. Premium subscriptions are billed
          monthly or annually through Stripe. You may cancel your subscription at any time; cancellation
          takes effect at the end of your current billing period. We do not offer refunds for partial
          billing periods.
        </p>

        <h2 style={h2Style}>6. Intellectual Property</h2>
        <p style={pStyle}>
          You retain ownership of the stories generated for your family through the Service. The Bedtime Virtues
          brand, design, book curation, and virtue framework are the intellectual property of Bedtime Virtues.
          The curated book library contains recommendations for third-party works; we do not claim
          ownership of those works.
        </p>

        <h2 style={h2Style}>7. Affiliate Programs</h2>
        <p style={pStyle}>
          Bedtime Virtues is a participant in the Amazon Services LLC Associates Program, an affiliate
          advertising program, and the Bookshop.org Affiliate Program. Links to books on Amazon and
          Bookshop.org are affiliate links, and we may earn commissions from qualifying purchases.
        </p>

        <h2 style={h2Style}>8. Prohibited Uses</h2>
        <p style={pStyle}>You agree not to:</p>
        <ul style={{ paddingLeft: 20, marginBottom: 16 }}>
          <li style={liStyle}>Use the Service to generate harmful, abusive, or inappropriate content.</li>
          <li style={liStyle}>Attempt to bypass rate limits, usage restrictions, or content safety measures.</li>
          <li style={liStyle}>Resell, redistribute, or commercially exploit generated stories without permission.</li>
          <li style={liStyle}>Provide false information about your identity or parental/guardian status.</li>
        </ul>

        <h2 style={h2Style}>9. Limitation of Liability</h2>
        <p style={pStyle}>
          The Service is provided &ldquo;as is&rdquo; without warranties of any kind. To the maximum extent
          permitted by law, Bedtime Virtues shall not be liable for any indirect, incidental, special,
          consequential, or punitive damages arising from your use of the Service, including but not
          limited to damages arising from AI-generated content.
        </p>

        <h2 style={h2Style}>10. Indemnification</h2>
        <p style={pStyle}>
          You agree to indemnify and hold harmless Bedtime Virtues from any claims, damages, or expenses
          arising from your use of the Service or violation of these Terms.
        </p>

        <h2 style={h2Style}>11. Changes to Terms</h2>
        <p style={pStyle}>
          We may update these Terms from time to time. Continued use of the Service after changes
          constitutes acceptance of the updated Terms.
        </p>

        <h2 style={h2Style}>12. Governing Law</h2>
        <p style={pStyle}>
          These Terms are governed by and construed in accordance with the laws of the Commonwealth of
          Virginia, without regard to conflict of law principles.
        </p>

        <h2 style={h2Style}>13. Contact</h2>
        <p style={pStyle}>
          For questions about these Terms, contact us at:
        </p>
        <p style={{ ...pStyle, fontWeight: 600 }}>
          hello@bedtimevirtues.com
        </p>

        <div style={{
          marginTop: 40, padding: 20, borderRadius: T.radius,
          background: T.gray50, border: `1px solid ${T.gray100}`,
        }}>
          <p style={{ fontFamily: T.fontSans, fontSize: 14, color: T.gray500, lineHeight: 1.6, margin: 0 }}>
            &copy; 2026 Bedtime Virtues. All rights reserved.
          </p>
        </div>
      </div>
    </div>
  );
}
